sudo: required
language: bash
env:
  global:
  - BUILD_NAME="UltraStar Play"
  - UNITYCI_PROJECT_NAME="UltraStar Play"
  
services:
- docker
  
# only run builds on pushes to the master branch
branches:
  only:
  - master

# send email notifications when the build changes from succeeding to broken
notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - chmod +x ./tools/travis/docker_test.sh
  - chmod +x ./tools/travis/docker_build.sh
  - chmod +x ./tools/travis/build.sh
  - chmod +x ./tools/travis/before_script.sh
  - chmod +x ./tools/travis/test.sh
  - chmod +x ./tools/download-dependencies/*.sh
  - (cd tools/download-dependencies/; sh download-dependencies.sh)
  - export UNITY_LICENSE_CONTENT=`cat tools/travis/activat.ion`
  - rm tools/travis/activat.ion
  - docker pull $IMAGE_NAME

jobs:
  include:
  - stage: test
    script: "./tools/travis/docker_test.sh"
    env: TEST_PLATFORM=editmode IMAGE_NAME=gableroux/unity3d:2019.2.11f1
    addons:
      artifacts:
        s3_region: "eu-west-1"
        paths:
        - "$(pwd)/$TEST_PLATFORM-results.xml"
  - stage: test
    script: "./tools/travis/docker_test.sh"
    env: TEST_PLATFORM=playmode IMAGE_NAME=gableroux/unity3d:2019.2.11f1
    addons:
      artifacts:
        s3_region: "eu-west-1"
        paths:
        - "$(pwd)/$TEST_PLATFORM-results.xml"
  - stage: build
    env: BUILD_TARGET=StandaloneLinux64 IMAGE_NAME=gableroux/unity3d:2019.2.11f1
    script: "./tools/travis/docker_build.sh"
    # no artifacts upload to reduce AWS S3 space usage and costs
  - stage: build
    env: BUILD_TARGET=StandaloneOSX IMAGE_NAME=gableroux/unity3d:2019.2.11f1-mac
    script: "./tools/travis/docker_build.sh"
  - stage: build
    env: BUILD_TARGET=StandaloneWindows64 IMAGE_NAME=gableroux/unity3d:2019.2.11f1-windows
    script: "./tools/travis/docker_build.sh"
    addons:
      artifacts:
        s3_region: "eu-west-1"
        paths:
        - "$(pwd)/UltraStarPlay-build.tar.gz"
